name: garagem-da-paulinha

services:
  app:
    container_name: garagem-da-paulinha-app
    hostname: garagem-da-paulinha-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_TELEMETRY_DISABLED: "1"
      HOSTNAME: "0.0.0.0"
      PORT: "3000"
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/app
      - garagem_da_paulinha_node_modules:/app/node_modules
      - garagem_da_paulinha_next:/app/.next
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  garagem_da_paulinha_node_modules:
  garagem_da_paulinha_next: